spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1
                url: jdbc:mysql://192.168.1.253:3306/dzkandian?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
                username: dzkandian
                password: dzkandian
            second:  #数据源2
                url: jdbc:mysql://192.168.1.253:3306/dzkandian?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
                username: dzkandian
                password: dzkandian
            third:  #数据源3
                url: jdbc:mysql://192.168.1.253:3306/dzkandian?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
                username: dzkandian
                password: dzkandian
            initial-size: 10
            max-active: 200
            min-idle: 10
            max-wait: 15000
            use-unfair-lock: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: admin
                login-password: tdnet
            filter:
                stat:
                    log-slow-sql: false
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
    redis:
        token:
            database: 1
            host: 192.168.1.254
            port: 6379
            password:       # 密码（默认为空）
            timeout: 6000  # 连接超时时长（毫秒）
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接
        cache:
            database: 0
            host: 192.168.1.254
            port: 6379
            password:       # 密码（默认为空）
            timeout: 6000  # 连接超时时长（毫秒）
            expiration: 30 # 默认过期时间（秒）
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接